name: "Build"
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://gcr.io/bazel-public/ubuntu1804:java11
        with:
          args: "bazel build //src:all"
      - uses: docker://gcr.io/bazel-public/ubuntu1804:java11
        with:
          args: "bazel test //src:all"
      - run: ls bazel-out/*/*/*/* && cat bazel-out/k8-fastbuild/testlogs/src/awscli_metadata_test/test.log
        if: failure()