name: "Build"
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://gcr.io/bazel-public/ubuntu1804:java11
        with:
          args: "bazel --output_base=/workspace/bazel_outputs build //src:awscli"
      - uses: docker://gcr.io/bazel-public/ubuntu1804:java11
        with:
          args: "bazel --output_base=/workspace/bazel_outputs test --test_output=all //src:all"